pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build("javaregistry01.azurecr.io/java-app:${env.BUILD_NUMBER}").push()
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "kubectl apply -f manifests/deployment.yaml"
                    sh "kubectl apply -f manifests/service.yaml"
                }
            }
        }
    }
}
